name: 'cloud_sandbox'
version: '1.0'

profile: 'cloud_sandbox'

source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

#remove when switching to postgres

quoting:
  database: false
  identifier: false
  schema: false
  

models:
  cloud_sandbox:
