version: 2

models:
  - name: stg_orders
    description: >
      This model renames columns from the `orders` seeded file.
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
          
  - name: stg_order_items
    description: >
      This model renames columns from the `order_items` seeded file.
    columns:
      - name: order_item_id
        tests:
          - not_null
          - unique
          
  - name: stg_customers
    description: >
      This model renames columns from the `customers` seeded file.
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique